/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

/**
 *
 * @author dam2_alu11@inf.ald
 */
public class SimpsonFrame extends javax.swing.JFrame {

    /**
     * Creates new form SimpsonFrame
     */
    public SimpsonFrame() {
        resizeWindow();
        initComponents();
        setColor();
        setColorRegistroPanel();
        setColorInicioSesionPanel();
        this.setTitle("Buscador principal");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        cumpleañosLabel = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        trabajoLabel = new javax.swing.JLabel();
        fraseLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        edadTextField = new javax.swing.JTextField();
        cumpleanhosTextField = new javax.swing.JTextField();
        fraseTextField = new javax.swing.JTextField();
        generoTextField = new javax.swing.JTextField();
        trabajoTextField = new javax.swing.JTextField();
        usuarioActivoLabel = new javax.swing.JLabel();
        buscarButton = new javax.swing.JButton();
        TITULOLabel = new javax.swing.JLabel();
        ocultarButton = new javax.swing.JButton();
        iniciarSesionButton = new javax.swing.JButton();
        crearCuentaPanel = new javax.swing.JPanel();
        usuarioRegistroTextField = new javax.swing.JTextField();
        usuarioRegistroLabel = new javax.swing.JLabel();
        contraseñaRegistroLabel = new javax.swing.JLabel();
        registrarseButton = new javax.swing.JButton();
        contraseñaRegistroTextField = new javax.swing.JPasswordField();
        iniciarSesionPanel = new javax.swing.JPanel();
        usuarioInicioSesionTextField = new javax.swing.JTextField();
        usuarioInicioSesionLabel = new javax.swing.JLabel();
        contraseñaInicioSesionLabel = new javax.swing.JLabel();
        accederButton = new javax.swing.JButton();
        contraseñaInicioSesionTextField = new javax.swing.JPasswordField();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        crearCuentaButton = new javax.swing.JButton();
        crearPersonajeButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        editarButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));

        nombreLabel.setFont(new java.awt.Font("Inter Regular", 1, 24)); // NOI18N
        nombreLabel.setText("Nombre:");

        edadLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edadLabel.setText("Edad:");

        cumpleañosLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cumpleañosLabel.setText("Cumpleaños:");

        generoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoLabel.setText("Género:");

        trabajoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trabajoLabel.setText("Trabajo:");

        fraseLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fraseLabel.setText("Frase:");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        edadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTextFieldActionPerformed(evt);
            }
        });

        cumpleanhosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumpleanhosTextFieldActionPerformed(evt);
            }
        });

        fraseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraseTextFieldActionPerformed(evt);
            }
        });

        generoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoTextFieldActionPerformed(evt);
            }
        });

        usuarioActivoLabel.setFont(new java.awt.Font("Inter Regular", 3, 24)); // NOI18N
        usuarioActivoLabel.setText("INVITADO");

        buscarButton.setBackground(new java.awt.Color(51, 51, 255));
        buscarButton.setFont(new java.awt.Font("Inter Regular", 3, 18)); // NOI18N
        buscarButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton.setText("BUSCAR");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        TITULOLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 30)); // NOI18N
        TITULOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpsonsapi.png"))); // NOI18N
        TITULOLabel.setText("SIMPSONSAPI");

        ocultarButton.setBackground(new java.awt.Color(0, 153, 102));
        ocultarButton.setFont(new java.awt.Font("Inter Regular", 3, 13)); // NOI18N
        ocultarButton.setForeground(new java.awt.Color(255, 255, 255));
        ocultarButton.setText("Ocultar");
        ocultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocultarButtonActionPerformed(evt);
            }
        });

        iniciarSesionButton.setBackground(new java.awt.Color(0, 153, 102));
        iniciarSesionButton.setFont(new java.awt.Font("Inter Regular", 3, 13)); // NOI18N
        iniciarSesionButton.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionButton.setText("Iniciar sesión");

        usuarioRegistroLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioRegistroLabel.setText("Usuario:");

        contraseñaRegistroLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contraseñaRegistroLabel.setText("Contraseña:");

        registrarseButton.setBackground(new java.awt.Color(0, 153, 102));
        registrarseButton.setFont(new java.awt.Font("Inter Regular", 3, 13)); // NOI18N
        registrarseButton.setForeground(new java.awt.Color(255, 255, 255));
        registrarseButton.setText("Registrarse");
        registrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearCuentaPanelLayout = new javax.swing.GroupLayout(crearCuentaPanel);
        crearCuentaPanel.setLayout(crearCuentaPanelLayout);
        crearCuentaPanelLayout.setHorizontalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearCuentaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarseButton)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearCuentaPanelLayout.createSequentialGroup()
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaRegistroLabel)
                    .addComponent(usuarioRegistroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioRegistroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(contraseñaRegistroTextField))
                .addGap(27, 27, 27))
        );
        crearCuentaPanelLayout.setVerticalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioRegistroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioRegistroLabel))
                .addGap(36, 36, 36)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaRegistroLabel)
                    .addComponent(contraseñaRegistroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(registrarseButton))
        );

        usuarioInicioSesionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioInicioSesionLabel.setText("Usuario:");

        contraseñaInicioSesionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contraseñaInicioSesionLabel.setText("Contraseña:");

        accederButton.setBackground(new java.awt.Color(0, 153, 102));
        accederButton.setFont(new java.awt.Font("Inter Regular", 3, 13)); // NOI18N
        accederButton.setForeground(new java.awt.Color(255, 255, 255));
        accederButton.setText("Acceder");
        accederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout iniciarSesionPanelLayout = new javax.swing.GroupLayout(iniciarSesionPanel);
        iniciarSesionPanel.setLayout(iniciarSesionPanelLayout);
        iniciarSesionPanelLayout.setHorizontalGroup(
            iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iniciarSesionPanelLayout.createSequentialGroup()
                        .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioInicioSesionLabel)
                            .addComponent(contraseñaInicioSesionLabel))
                        .addGap(26, 26, 26)
                        .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioInicioSesionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(contraseñaInicioSesionTextField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iniciarSesionPanelLayout.createSequentialGroup()
                        .addComponent(accederButton)
                        .addGap(115, 115, 115))))
        );
        iniciarSesionPanelLayout.setVerticalGroup(
            iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarSesionPanelLayout.createSequentialGroup()
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioInicioSesionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioInicioSesionLabel))
                .addGap(39, 39, 39)
                .addGroup(iniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaInicioSesionLabel)
                    .addComponent(contraseñaInicioSesionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addComponent(accederButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDLabel.setText("ID:");

        crearCuentaButton.setBackground(new java.awt.Color(0, 153, 102));
        crearCuentaButton.setFont(new java.awt.Font("Inter Regular", 3, 13)); // NOI18N
        crearCuentaButton.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton.setText("Crear cuenta");
        crearCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButtonActionPerformed(evt);
            }
        });

        crearPersonajeButton.setBackground(new java.awt.Color(51, 51, 255));
        crearPersonajeButton.setFont(new java.awt.Font("Inter Regular", 3, 18)); // NOI18N
        crearPersonajeButton.setForeground(new java.awt.Color(255, 255, 255));
        crearPersonajeButton.setText("CREAR PERSONAJE ");

        borrarButton.setBackground(new java.awt.Color(51, 51, 255));
        borrarButton.setFont(new java.awt.Font("Inter Regular", 3, 18)); // NOI18N
        borrarButton.setForeground(new java.awt.Color(255, 255, 255));
        borrarButton.setText("BORRAR");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        editarButton1.setBackground(new java.awt.Color(51, 51, 255));
        editarButton1.setFont(new java.awt.Font("Inter Regular", 3, 18)); // NOI18N
        editarButton1.setForeground(new java.awt.Color(255, 255, 255));
        editarButton1.setText("EDITAR");
        editarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciarSesionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(crearCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(trabajoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(trabajoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(generoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fraseLabel)
                                                .addGap(60, 60, 60)
                                                .addComponent(fraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edadLabel)
                                            .addComponent(IDLabel))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cumpleañosLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cumpleanhosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(iniciarSesionButton)
                        .addGap(121, 121, 121)
                        .addComponent(ocultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(crearCuentaButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TITULOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(usuarioActivoLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(322, 322, 322))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(crearPersonajeButton)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioActivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLabel)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trabajoLabel)
                            .addComponent(trabajoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoLabel)
                            .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cumpleañosLabel)
                            .addComponent(cumpleanhosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fraseLabel)
                        .addComponent(fraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciarSesionButton)
                            .addComponent(crearCuentaButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocultarButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crearCuentaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(iniciarSesionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(crearPersonajeButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTextFieldActionPerformed

    private void fraseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fraseTextFieldActionPerformed

    private void generoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoTextFieldActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void ocultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocultarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocultarButtonActionPerformed

    private void registrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarseButtonActionPerformed

    private void accederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accederButtonActionPerformed

    private void cumpleanhosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumpleanhosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cumpleanhosTextFieldActionPerformed

    private void crearCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void editarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addBuscarActionListener(ActionListener al) {

        this.buscarButton.addActionListener(al);

    }

    public void addIniciarSesionActionListener(ActionListener al) {

        this.iniciarSesionButton.addActionListener(al);
    }

    public void addCrearCuenta(ActionListener al) {

        this.crearCuentaButton.addActionListener(al);
    }

    public void addRegistrarseActionListener(ActionListener al) {

        this.registrarseButton.addActionListener(al);
    }

    public void addAccederActionListener(ActionListener al) {

        this.accederButton.addActionListener(al);

    }

    public void addOcultarActionListener(ActionListener al) {

        this.ocultarButton.addActionListener(al);
    }

    public void addCrearPersonajeActionListener(ActionListener al) {

        this.crearPersonajeButton.addActionListener(al);
    }
       public void addBorrarPersonajeActionListener(ActionListener al) {

        this.borrarButton.addActionListener(al);
    }
       public void addEditarPersonajeActionListener(ActionListener al){
       
        this.editarButton1.addActionListener(al);
       }

    public void resizeWindow() {

        this.getContentPane().setLayout(null);
    }

    public void setFondo() {

        this.getContentPane().createImage(WIDTH, HEIGHT);
    }

    public void setColor() {

        this.getContentPane().setBackground(new Color(255,220,0));
    }
     

    public void setColorRegistroPanel() {
        this.crearCuentaPanel.setBackground(new Color(255,220,0));

    }

    public void setColorInicioSesionPanel() {
        this.iniciarSesionPanel.setBackground(new Color(255,220,0));

    }

    public void setVisibleButtonInicioSesion(Boolean b) {

        this.iniciarSesionPanel.setVisible(b);

    }

    public void setVisibleButtonCrearCuenta(Boolean b) {

        this.crearCuentaPanel.setVisible(b);
    }

    public void initComponentes() {

        this.iniciarSesionPanel.setVisible(false);
        this.crearCuentaPanel.setVisible(false);

    }
    public String getEdad(){
        return this.edadTextField.getText();
    }
    public String getId(){
        return this.IDTextField.getText();
    }
    public String getCumpleaños(){
        return this.cumpleanhosTextField.getText();
    }
     public String getTrabajo(){
        return this.trabajoTextField.getText();
    }
      public String getGenero(){
        return this.generoTextField.getText();
    }
     public String getFrase(){
         return this.fraseTextField.getText();
     }
     public void  bloquearCampoId(){
         this.IDTextField.setEditable(false);
     }
   

    public String getNombre() {

        return this.nombreTextField.getText();
    }

    public void setID(int id) {

        this.IDTextField.setText(Integer.toString(id));
    }

    public void setEdad(int edad) {

        this.edadTextField.setText(Integer.toString(edad));
    }

    public void setCumpleanhos(String cumpleanhos) {

        this.cumpleanhosTextField.setText(cumpleanhos);
    }

    public void setTrabajo(String trabajo) {
        this.trabajoTextField.setText(trabajo);

    }
    
    public void setName(String name){
    
        this.nombreTextField.setText(name);
    }

    public void setGenero(String genero) {

        this.generoTextField.setText(genero);
    }
    public void setContraseñaInicio(String contraseña) {

        this.contraseñaInicioSesionTextField.setText(contraseña);
    }
    
 public void setContraseñaRegistro(String contraseña) {

        this.contraseñaRegistroTextField.setText(contraseña);
    }
  public void setUsuarioInicioSesion(String usuario) {

        this.usuarioInicioSesionTextField.setText(usuario);
    }
   public void setUsuarioRegistro(String usuario) {

        this.usuarioRegistroTextField.setText(usuario);
    }
    public void setFrase(String frase) {

        this.fraseTextField.setText(frase);
    }
    
    public String getUsuarioRegistroTextField(){
        return this.usuarioRegistroTextField.getText();
    }
    
    public String getContraseñaRegistroTextField(){
        return this.contraseñaRegistroTextField.getText();
    }
    
    public String getUsuarioIniciarTextField(){
        return this.usuarioInicioSesionTextField.getText();
    }
    
    public String getContraseñaIniciarTextField(){
        return this.contraseñaInicioSesionTextField.getText();
    }
    
    public String getUsuarioActivoLabel(){
    
        return this.usuarioActivoLabel.getText();
    }
    
    public void setUsuarioActivoLabel(String text){
        this.usuarioActivoLabel.setText(text);
    }
    
    public void clearID() {
    this.IDTextField.setText("");
}

public void clearEdad() {
    this.edadTextField.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel TITULOLabel;
    private javax.swing.JButton accederButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel contraseñaInicioSesionLabel;
    private javax.swing.JPasswordField contraseñaInicioSesionTextField;
    private javax.swing.JLabel contraseñaRegistroLabel;
    private javax.swing.JPasswordField contraseñaRegistroTextField;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JPanel crearCuentaPanel;
    private javax.swing.JButton crearPersonajeButton;
    private javax.swing.JTextField cumpleanhosTextField;
    private javax.swing.JLabel cumpleañosLabel;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JTextField edadTextField;
    private javax.swing.JButton editarButton1;
    private javax.swing.JLabel fraseLabel;
    private javax.swing.JTextField fraseTextField;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JButton iniciarSesionButton;
    private javax.swing.JPanel iniciarSesionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton ocultarButton;
    private javax.swing.JButton registrarseButton;
    private javax.swing.JLabel trabajoLabel;
    private javax.swing.JTextField trabajoTextField;
    private javax.swing.JLabel usuarioActivoLabel;
    private javax.swing.JLabel usuarioInicioSesionLabel;
    private javax.swing.JTextField usuarioInicioSesionTextField;
    private javax.swing.JLabel usuarioRegistroLabel;
    private javax.swing.JTextField usuarioRegistroTextField;
    // End of variables declaration//GEN-END:variables
}
